apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
        - name: {{ .Release.Name }}-container
          image: {{ .Values.image.svcimage }}
          volumeMounts:
            - mountPath: /var/www/html/images
              name: {{ .Release.Name }}-volume
          ports:
            - containerPort: 80
      volumes:
        - name: {{ .Release.Name }}-volume
