apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app: {{ .Release.Name }}-app
spec:
  type: {{ .Values.service.apptype }}
  ports:
    - port: {{ .Values.service.appPort }}
      nodePort: {{ .Values.service.appNodePort }}
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-app
